# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS
  pod 'Alamofire', '~> 5.5'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FirebaseAuth'
  pod 'FSCalendar'
  pod 'CalendarDateRangePicker'


  target 'iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSUITests' do
    # Pods for testing
  end

end
