# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS
  pod 'Alamofire', '~> 5.5'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FirebaseAuth'
  pod 'FSCalendar'
  pod 'CalendarDateRangePicker'
  pod 'GoogleSignIn'

  target 'iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
  end

end
